spring.application.name=NexusHR

spring.datasource.url=jdbc:mysql://localhost:3306/nexushr_db
spring.datasource.username=root
spring.datasource.password=Thaneem@2004

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jkausar004@gmail.com
spring.mail.password=yiuxvkymqrgvvrlm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name= itd7fbsp
cloudinary.api-key=916724437277228
cloudinary.api-secret=8QMrVTAT0FsUjB88jmSOvCcn_-k